docs(ch21): added documentation for commit formatting, tag, release and publish workflows
theartofeducation/engineering-docs pull request #2
Opened 2020-11-13 19:22 UTC by ryexley

[CH21](https://app.clubhouse.io/aoeu-se/story/21/setup-and-configure-to-publish-to-github-package-registry)

This PR adds documentation for the following process/procedures:

* Commit message formatting
* Tag, Release and Publish workflows
* Story Point Sizing

2020-11-13 20:15 UTC, Thomas-Jean requested changes

2020-11-13 20:15 UTC, Thomas-Jean commented on docs/commit-format.mdx
> +* refactor` - changes that refactor existing code
missing `

2020-11-13 20:35 UTC, Thomas-Jean submitted a review, later dismissed

2020-11-13 21:27 UTC, Thomas-Jean approved these changes

2020-11-16 11:45 UTC, theantichris approved these changes

2020-11-16 13:18 UTC, merged