chore/ch4556/document new software development lifecycle
theartofeducation/engineering-docs pull request #44
Opened 2021-09-09 16:55 UTC by theantichris

- refactor: removed backlog, refined other steps
- feature: added notes about libraries
- feature: added backlog and updated qa process

2021-09-09 20:37 UTC, racheljay submitted a review, later dismissed

2021-09-10 13:35 UTC, ryexley approved these changes
Thanks for updating this 🙇🏼

2021-09-10 15:59 UTC, ryexley approved these changes

2021-09-10 17:54 UTC, racheljay approved these changes

2021-09-13 13:04 UTC, jmosley5 requested changes
Looks good other than the one change requested 👍🏼

2021-09-13 13:04 UTC, jmosley5 commented on docs/software-development-lifecycle.mdx
> +    * When an engineer is ready for a new story they will take one from this column this column and assign it to the current iteration
"this column" appears twice

2021-09-13 13:50 UTC, rlmead commented on docs/software-development-lifecycle.mdx
> +    * Creating a Git branch referrencing the story ID will automatically move the story to the **In Development** column
Typo: "referrencing" -> "referencing"

2021-09-13 13:50 UTC, rlmead commented on docs/software-development-lifecycle.mdx
> +    * The enginer opens a Pull Request from their feature branch into `develop`
Typo: "enginer" -> "engineer"

2021-09-13 13:51 UTC, racheljay submitted a review, later dismissed

2021-09-13 14:55 UTC, jmosley5 approved these changes
:shipit:

2021-09-13 15:44 UTC, racheljay approved these changes

2021-09-14 12:19 UTC, ryexley approved these changes

2021-09-14 12:37 UTC, merged